name: CI

on:
  [ push, pull_request]

jobs:
  lint_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses:  actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Setup environment
        run: |
          pip install setuptools wheel
          pip install numpy
          pip install -e .
          
      - name: flake
        run: |
          pip install flake8
          flake8
        
